### ISSUE TITLE
Top Line not Aligned 

### ISSUE THREAD

**Issue by untraceablez** [untraceablez/qlocktwo#1]
![screenshot](https://cloud.githubusercontent.com/assets/2263090/3668271/105040f4-1218-11e4-8b42-3a15f75192a1.png)  

As seen in the picture, the top line of the word display is not aligned.

**Comment by javakrypt** [comment]
When I install this, mine looks nothing like your picture. Is it because I'm using a different system font than the default one in Mavericks? It also displays times after half past wrong. It says "It is # OF #" instead of TO like your picture.

![screen shot 2014-08-14 at 02 57 40](https://cloud.githubusercontent.com/assets/1444807/3915130/faaf2abc-2356-11e4-9783-6b714fb2aed6.PNG)

**Comment by untraceablez** [comment]
- At the moment I'm running the Yosemite Public Beta, so that might be part of the underlying issue as to why yours is so wildly different. 
- That being said, your default system font shouldn't matter, as this geeklet uses a specific font anyway.  
- Is your default language a dialect of English? That's the first thing to come off the top of my head. I'll dig in the ruby script and see if it has the 'of' alternate in it somewhere.

**Comment by javakrypt** [comment]
Ah okay, so this was designed using Yosemite for Yosemite? My language is set to English, UK.

**Comment by untraceablez** [comment]
Well, it was designed for OS X, I figured that the ruby output wouldn't really change between the two releases. Apparently I was wrong. :P 

And the 'of' is produced by the ruby script, it might be defaulting to that because you're set to UK English. (Not sure why it would, but I designed it using US English)

I'm going to quickly edit the 'of'. Just watch for a commit and re-do it, will probably patch up that issue.

**Comment by untraceablez** [comment]
Stale

**Comment by untraceablez** [comment]
Stale, closing

**Comment by untraceablez** [comment]
Stale, closing
